# Generated by Django 3.0.8 on 2020-07-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200723_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
    ]
